language: python
python:
 - "3.5"
 # command to install dependencies
install:
  - pip install requests
  - pip install nose

# command to run tests
script:
 - cd ./hw04a && python -m unittest && nosetests --verbosity=2
